[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
ai-types = "0.2.0"
axum = { version = "0.8.4", features = ["ws"] }
tower-service = "0.3.3"
worker = { version = "0.6.0", features = ["http"] }
